//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Calculations.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Calculations.General.Resou" +
                            "rces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Header {
            get {
                return ResourceManager.GetString("Description_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulations To Run.
        /// </summary>
        public static string ElementName_SimulationsToRun {
            get {
                return ResourceManager.GetString("ElementName_SimulationsToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel calculation.
        /// </summary>
        public static string Footer_CancelCalculation {
            get {
                return ResourceManager.GetString("Footer_CancelCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string Footer_Progress {
            get {
                return ResourceManager.GetString("Footer_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calculation.
        /// </summary>
        public static string Footer_RunCalculation {
            get {
                return ResourceManager.GetString("Footer_RunCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Header_Header {
            get {
                return ResourceManager.GetString("Header_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulations to run:.
        /// </summary>
        public static string Header_SimulationsToRun {
            get {
                return ResourceManager.GetString("Header_SimulationsToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Result_ChartAxisY_Title {
            get {
                return ResourceManager.GetString("Result_ChartAxisY_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental probability =.
        /// </summary>
        public static string Result_FinalResult_Probability {
            get {
                return ResourceManager.GetString("Result_FinalResult_Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide - Progress results.
        /// </summary>
        public static string Results_ProgressResultsExpander_Hide {
            get {
                return ResourceManager.GetString("Results_ProgressResultsExpander_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show - Progress results.
        /// </summary>
        public static string Results_ProgressResultsExpander_Show {
            get {
                return ResourceManager.GetString("Results_ProgressResultsExpander_Show", resourceCulture);
            }
        }
    }
}
