//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.DiceResources", typeof(DiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a dice.
        /// </summary>
        public static string ComboBox_DiceSelection_Text {
            get {
                return ResourceManager.GetString("ComboBox_DiceSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Roll.
        /// </summary>
        public static string ElementName_DiceRoll {
            get {
                return ResourceManager.GetString("ElementName_DiceRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Dice Rolls.
        /// </summary>
        public static string ElementName_DiceRolls {
            get {
                return ResourceManager.GetString("ElementName_DiceRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Type.
        /// </summary>
        public static string ElementName_DiceType {
            get {
                return ResourceManager.GetString("ElementName_DiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice type: .
        /// </summary>
        public static string Label_DiceSelection_Content {
            get {
                return ResourceManager.GetString("Label_DiceSelection_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dice rolls:.
        /// </summary>
        public static string Label_NumberOfDiceRolls_Content {
            get {
                return ResourceManager.GetString("Label_NumberOfDiceRolls_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sides:.
        /// </summary>
        public static string Label_NumberOfSides_Content {
            get {
                return ResourceManager.GetString("Label_NumberOfSides_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a side:.
        /// </summary>
        public static string Label_SideSelection_Content {
            get {
                return ResourceManager.GetString("Label_SideSelection_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to side rolled is.
        /// </summary>
        public static string String_CalculationAction {
            get {
                return ResourceManager.GetString("String_CalculationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six sided die.
        /// </summary>
        public static string String_DiceType_Cube {
            get {
                return ResourceManager.GetString("String_DiceType_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve sided die.
        /// </summary>
        public static string String_DiceType_Dodecahedron {
            get {
                return ResourceManager.GetString("String_DiceType_Dodecahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty sided die.
        /// </summary>
        public static string String_DiceType_Icosahedron {
            get {
                return ResourceManager.GetString("String_DiceType_Icosahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight sided die.
        /// </summary>
        public static string String_DiceType_Octahedron {
            get {
                return ResourceManager.GetString("String_DiceType_Octahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten sided die.
        /// </summary>
        public static string String_DiceType_PentagonalTrapezohedron {
            get {
                return ResourceManager.GetString("String_DiceType_PentagonalTrapezohedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four sided die.
        /// </summary>
        public static string String_DiceType_Tetrahedron {
            get {
                return ResourceManager.GetString("String_DiceType_Tetrahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sided die..
        /// </summary>
        public static string String_PoolItem {
            get {
                return ResourceManager.GetString("String_PoolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die, that can have four, six, eight, ten, twelve or twenty sides..
        /// </summary>
        public static string String_TypeInfo {
            get {
                return ResourceManager.GetString("String_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: Dice.
        /// </summary>
        public static string String_TypeName {
            get {
                return ResourceManager.GetString("String_TypeName", resourceCulture);
            }
        }
    }
}
