//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel calculation.
        /// </summary>
        public static string Button_CancelCalculation_Content {
            get {
                return ResourceManager.GetString("Button_CancelCalculation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calculation.
        /// </summary>
        public static string Button_RunCalculation_Content {
            get {
                return ResourceManager.GetString("Button_RunCalculation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a type.
        /// </summary>
        public static string ComboBox_TypeSelection_Text {
            get {
                return ResourceManager.GetString("ComboBox_TypeSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulations To Run.
        /// </summary>
        public static string ElementName_SimulationsToRun {
            get {
                return ResourceManager.GetString("ElementName_SimulationsToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value given in.
        /// </summary>
        public static string Error_Number_Beginning {
            get {
                return ResourceManager.GetString("Error_Number_Beginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has exceeded the maximal value of.
        /// </summary>
        public static string Error_Number_Max {
            get {
                return ResourceManager.GetString("Error_Number_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has not exceeded the minimal value of.
        /// </summary>
        public static string Error_Number_Min {
            get {
                return ResourceManager.GetString("Error_Number_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental probability: .
        /// </summary>
        public static string Label_ExperimentalProbability_Content {
            get {
                return ResourceManager.GetString("Label_ExperimentalProbability_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simulations to run:.
        /// </summary>
        public static string Label_SimulationsToRun_Content {
            get {
                return ResourceManager.GetString("Label_SimulationsToRun_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighth result.
        /// </summary>
        public static string Label_TableColumnHeaderEighth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderEighth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth result.
        /// </summary>
        public static string Label_TableColumnHeaderFifth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderFifth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First result.
        /// </summary>
        public static string Label_TableColumnHeaderFirst_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderFirst_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth result.
        /// </summary>
        public static string Label_TableColumnHeaderFourth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderFourth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth result.
        /// </summary>
        public static string Label_TableColumnHeaderNinth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderNinth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second result.
        /// </summary>
        public static string Label_TableColumnHeaderSecond_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderSecond_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh result.
        /// </summary>
        public static string Label_TableColumnHeaderSeventh_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderSeventh_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth result.
        /// </summary>
        public static string Label_TableColumnHeaderSixth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderSixth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenth result.
        /// </summary>
        public static string Label_TableColumnHeaderTenth_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderTenth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third result.
        /// </summary>
        public static string Label_TableColumnHeaderThird_Content {
            get {
                return ResourceManager.GetString("Label_TableColumnHeaderThird_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition met.
        /// </summary>
        public static string Label_TableRowHeaderConditionsMet_Content {
            get {
                return ResourceManager.GetString("Label_TableRowHeaderConditionsMet_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        public static string Label_TableRowHeaderProbability_Content {
            get {
                return ResourceManager.GetString("Label_TableRowHeaderProbability_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulations ran.
        /// </summary>
        public static string Label_TableRowHeaderSimulationsRan_Content {
            get {
                return ResourceManager.GetString("Label_TableRowHeaderSimulationsRan_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Label_TypeSelection_Content {
            get {
                return ResourceManager.GetString("Label_TypeSelection_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Caption_Error {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBox_Caption_Information {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The running calculation was canceled..
        /// </summary>
        public static string MessageBox_Message_CalculationCanceled {
            get {
                return ResourceManager.GetString("MessageBox_Message_CalculationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition you are looking for is that.
        /// </summary>
        public static string String_ConditionInfo {
            get {
                return ResourceManager.GetString("String_ConditionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string String_IndefiniteMember_A {
            get {
                return ResourceManager.GetString("String_IndefiniteMember_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        public static string String_IndefiniteMember_An {
            get {
                return ResourceManager.GetString("String_IndefiniteMember_An", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string String_NotAvailable {
            get {
                return ResourceManager.GetString("String_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the pool is made out of.
        /// </summary>
        public static string String_PoolInfo {
            get {
                return ResourceManager.GetString("String_PoolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This calculation works with a pool, that consists of a.
        /// </summary>
        public static string String_TypeInfo {
            get {
                return ResourceManager.GetString("String_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition settings.
        /// </summary>
        public static string TextBlock_ConditionHeader2_Text {
            get {
                return ResourceManager.GetString("TextBlock_ConditionHeader2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation description.
        /// </summary>
        public static string TextBlock_DescriptionHeader1_Text {
            get {
                return ResourceManager.GetString("TextBlock_DescriptionHeader1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool visualization.
        /// </summary>
        public static string TextBlock_DescriptionHeader2_Text {
            get {
                return ResourceManager.GetString("TextBlock_DescriptionHeader2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. After the calculation completes, you can repeat these steps indefinitely or close the application..
        /// </summary>
        public static string TextBlock_FifthStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_FifthStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Choose the type of calculation you want to work with..
        /// </summary>
        public static string TextBlock_FirstStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_FirstStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1. If any errors pop up follow the given instructions..
        /// </summary>
        public static string TextBlock_FourthFirstStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_FourthFirstStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.2. If no errors pop up wait for all results..
        /// </summary>
        public static string TextBlock_FourthSecondStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_FourthSecondStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Run the calculation and see what happens..
        /// </summary>
        public static string TextBlock_FourthStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_FourthStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the pool is made out of a.
        /// </summary>
        public static string TextBlock_PoolDescription_Text {
            get {
                return ResourceManager.GetString("TextBlock_PoolDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last calculation results.
        /// </summary>
        public static string TextBlock_ResultsHeader1_Text {
            get {
                return ResourceManager.GetString("TextBlock_ResultsHeader1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Set the calculation type settings to your liking..
        /// </summary>
        public static string TextBlock_SecondStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_SecondStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation settings.
        /// </summary>
        public static string TextBlock_SettingsHeader1_Text {
            get {
                return ResourceManager.GetString("TextBlock_SettingsHeader1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Set the calculation condition settings to your liking..
        /// </summary>
        public static string TextBlock_ThirdStep_Text {
            get {
                return ResourceManager.GetString("TextBlock_ThirdStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief tutorial.
        /// </summary>
        public static string TextBlock_TutorialHeader1_Text {
            get {
                return ResourceManager.GetString("TextBlock_TutorialHeader1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type settings.
        /// </summary>
        public static string TextBlock_TypeHeader2_Text {
            get {
                return ResourceManager.GetString("TextBlock_TypeHeader2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Window_Icon {
            get {
                object obj = ResourceManager.GetObject("Window_Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Probability.
        /// </summary>
        public static string Window_MainWindow_Title {
            get {
                return ResourceManager.GetString("Window_MainWindow_Title", resourceCulture);
            }
        }
    }
}
