//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take three different balls in a row.
        /// </summary>
        internal static string BagOfColoredBalls_Condition_First {
            get {
                return ResourceManager.GetString("BagOfColoredBalls_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take three identical balls in a row.
        /// </summary>
        internal static string BagOfColoredBalls_Condition_Second {
            get {
                return ResourceManager.GetString("BagOfColoredBalls_Condition_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calculation.
        /// </summary>
        internal static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Condition_NotAvailable {
            get {
                return ResourceManager.GetString("Condition_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition is true if all three of the taken balls are a different color..
        /// </summary>
        internal static string Description_BagOfColoredBalls_Condition_First {
            get {
                return ResourceManager.GetString("Description_BagOfColoredBalls_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition is true if all three of the taken balls are the same color..
        /// </summary>
        internal static string Description_BagOfColoredBalls_Condition_Second {
            get {
                return ResourceManager.GetString("Description_BagOfColoredBalls_Condition_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of calculation works with a six-sided dice..
        /// </summary>
        internal static string Description_DiceRoll {
            get {
                return ResourceManager.GetString("Description_DiceRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition is true if the dice is rolled once and the rolled side has the number six on it..
        /// </summary>
        internal static string Description_DiceRoll_Condition_First {
            get {
                return ResourceManager.GetString("Description_DiceRoll_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition is true if the dice is rolled twice and both rolled sides have the number six on them..
        /// </summary>
        internal static string Description_DiceRoll_Condition_Second {
            get {
                return ResourceManager.GetString("Description_DiceRoll_Condition_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of calculation works with a bag filled with nine colored balls..
        /// </summary>
        internal static string Desription_BagOfColoredBalls {
            get {
                return ResourceManager.GetString("Desription_BagOfColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll a six.
        /// </summary>
        internal static string DiceRoll_Condition_First {
            get {
                return ResourceManager.GetString("DiceRoll_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll two sixes in a row.
        /// </summary>
        internal static string DiceRoll_Condition_Second {
            get {
                return ResourceManager.GetString("DiceRoll_Condition_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation description.
        /// </summary>
        internal static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of calculation condition:.
        /// </summary>
        internal static string Header_Description_Condition {
            get {
                return ResourceManager.GetString("Header_Description_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of calculation type:.
        /// </summary>
        internal static string Header_Description_Type {
            get {
                return ResourceManager.GetString("Header_Description_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last calculation results.
        /// </summary>
        internal static string Header_Results {
            get {
                return ResourceManager.GetString("Header_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation settings.
        /// </summary>
        internal static string Header_Settings {
            get {
                return ResourceManager.GetString("Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000.
        /// </summary>
        internal static string Simulations_Default {
            get {
                return ResourceManager.GetString("Simulations_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times..
        /// </summary>
        internal static string String_Times {
            get {
                return ResourceManager.GetString("String_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition:.
        /// </summary>
        internal static string Text_Condition {
            get {
                return ResourceManager.GetString("Text_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition was met.
        /// </summary>
        internal static string Text_ConditionsMet {
            get {
                return ResourceManager.GetString("Text_ConditionsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of condition is.
        /// </summary>
        internal static string Text_Probability {
            get {
                return ResourceManager.GetString("Text_Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of simulations:.
        /// </summary>
        internal static string Text_Simulations {
            get {
                return ResourceManager.GetString("Text_Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation ran.
        /// </summary>
        internal static string Text_SimulationsRun {
            get {
                return ResourceManager.GetString("Text_SimulationsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Text_Type {
            get {
                return ResourceManager.GetString("Text_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag of colored balls.
        /// </summary>
        internal static string Type_BagOfColoredBalls {
            get {
                return ResourceManager.GetString("Type_BagOfColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice roll.
        /// </summary>
        internal static string Type_DiceRoll {
            get {
                return ResourceManager.GetString("Type_DiceRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Type_Empty {
            get {
                return ResourceManager.GetString("Type_Empty", resourceCulture);
            }
        }
    }
}
