//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calculation.
        /// </summary>
        internal static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Color_Black {
            get {
                return ResourceManager.GetString("Color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Color_Brown {
            get {
                return ResourceManager.GetString("Color_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string Color_Violet {
            get {
                return ResourceManager.GetString("Color_Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Color_White {
            get {
                return ResourceManager.GetString("Color_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Color_Yellow {
            get {
                return ResourceManager.GetString("Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take three different balls in a row.
        /// </summary>
        internal static string ColoredBalls_Condition_First {
            get {
                return ResourceManager.GetString("ColoredBalls_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Condition_NotAvailable {
            get {
                return ResourceManager.GetString("Condition_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Default_ColoredBalls_NumberOfColors {
            get {
                return ResourceManager.GetString("Default_ColoredBalls_NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Default_Condition_ColoredBalls_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Default_Condition_ColoredBalls_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Default_Condition_Dice_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Default_Condition_Dice_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Default_Pool_Size_ColoredBalls {
            get {
                return ResourceManager.GetString("Default_Pool_Size_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Default_Pool_Size_Dice {
            get {
                return ResourceManager.GetString("Default_Pool_Size_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000.
        /// </summary>
        internal static string Default_Simulations {
            get {
                return ResourceManager.GetString("Default_Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll a six.
        /// </summary>
        internal static string Dice_Condition_First {
            get {
                return ResourceManager.GetString("Dice_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation description.
        /// </summary>
        internal static string Header1_Description_Calculation {
            get {
                return ResourceManager.GetString("Header1_Description_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last calculation results.
        /// </summary>
        internal static string Header1_Results {
            get {
                return ResourceManager.GetString("Header1_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation settings.
        /// </summary>
        internal static string Header1_Settings_Calculation {
            get {
                return ResourceManager.GetString("Header1_Settings_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of calculation condition:.
        /// </summary>
        internal static string Header2_Description_Condition {
            get {
                return ResourceManager.GetString("Header2_Description_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of calculation type:.
        /// </summary>
        internal static string Header2_Description_Type {
            get {
                return ResourceManager.GetString("Header2_Description_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition settings.
        /// </summary>
        internal static string Header2_Settings_Condition {
            get {
                return ResourceManager.GetString("Header2_Settings_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type settings.
        /// </summary>
        internal static string Header2_Settings_Type {
            get {
                return ResourceManager.GetString("Header2_Settings_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool settings.
        /// </summary>
        internal static string Header3_Settings_Pool {
            get {
                return ResourceManager.GetString("Header3_Settings_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Probability.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times..
        /// </summary>
        internal static string String_Times {
            get {
                return ResourceManager.GetString("String_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal number of colors.
        /// </summary>
        internal static string Text_ColoredBalls_Check_EqualNumberOfColors {
            get {
                return ResourceManager.GetString("Text_ColoredBalls_Check_EqualNumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color number.
        /// </summary>
        internal static string Text_ColoredBalls_Color {
            get {
                return ResourceManager.GetString("Text_ColoredBalls_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors:.
        /// </summary>
        internal static string Text_ColoredBalls_NumberOfColors {
            get {
                return ResourceManager.GetString("Text_ColoredBalls_NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition:.
        /// </summary>
        internal static string Text_Condition {
            get {
                return ResourceManager.GetString("Text_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of taken balls:.
        /// </summary>
        internal static string Text_Condition_ColoredBalls_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Text_Condition_ColoredBalls_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dice rolls:.
        /// </summary>
        internal static string Text_Condition_Dice_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Text_Condition_Dice_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition was met.
        /// </summary>
        internal static string Text_ConditionsMet {
            get {
                return ResourceManager.GetString("Text_ConditionsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side number.
        /// </summary>
        internal static string Text_Dice_Side {
            get {
                return ResourceManager.GetString("Text_Dice_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of balls:.
        /// </summary>
        internal static string Text_Pool_Size_ColoredBalls {
            get {
                return ResourceManager.GetString("Text_Pool_Size_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of sides:.
        /// </summary>
        internal static string Text_Pool_Size_Dice {
            get {
                return ResourceManager.GetString("Text_Pool_Size_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of condition is.
        /// </summary>
        internal static string Text_Probability {
            get {
                return ResourceManager.GetString("Text_Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color.
        /// </summary>
        internal static string Text_Selection_ColoredBalls_Color {
            get {
                return ResourceManager.GetString("Text_Selection_ColoredBalls_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a side.
        /// </summary>
        internal static string Text_Selection_Dice_Side {
            get {
                return ResourceManager.GetString("Text_Selection_Dice_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a type.
        /// </summary>
        internal static string Text_Selection_Type {
            get {
                return ResourceManager.GetString("Text_Selection_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of simulations:.
        /// </summary>
        internal static string Text_Simulations {
            get {
                return ResourceManager.GetString("Text_Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation ran.
        /// </summary>
        internal static string Text_SimulationsRun {
            get {
                return ResourceManager.GetString("Text_SimulationsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: Colored balls.
        /// </summary>
        internal static string Type_ColoredBalls {
            get {
                return ResourceManager.GetString("Type_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: Dice.
        /// </summary>
        internal static string Type_Dice {
            get {
                return ResourceManager.GetString("Type_Dice", resourceCulture);
            }
        }
    }
}
