//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calculation.
        /// </summary>
        public static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Color_Black {
            get {
                return ResourceManager.GetString("Color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Color_Brown {
            get {
                return ResourceManager.GetString("Color_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Color_Gray {
            get {
                return ResourceManager.GetString("Color_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string Color_Violet {
            get {
                return ResourceManager.GetString("Color_Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string Color_White {
            get {
                return ResourceManager.GetString("Color_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Color_Yellow {
            get {
                return ResourceManager.GetString("Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take three different balls in a row.
        /// </summary>
        public static string ColoredBalls_Condition_First {
            get {
                return ResourceManager.GetString("ColoredBalls_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Default_ColoredBalls_ColorNumber {
            get {
                return ResourceManager.GetString("Default_ColoredBalls_ColorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Default_ColoredBalls_NumberOfColors {
            get {
                return ResourceManager.GetString("Default_ColoredBalls_NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Default_Condition_ColoredBalls_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Default_Condition_ColoredBalls_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Default_Condition_Dice_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Default_Condition_Dice_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Default_Pool_Size_ColoredBalls {
            get {
                return ResourceManager.GetString("Default_Pool_Size_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Default_Pool_Size_Dice {
            get {
                return ResourceManager.GetString("Default_Pool_Size_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color.
        /// </summary>
        public static string Default_Selection_ColoredBalls {
            get {
                return ResourceManager.GetString("Default_Selection_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a side.
        /// </summary>
        public static string Default_Selection_Dice {
            get {
                return ResourceManager.GetString("Default_Selection_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a type.
        /// </summary>
        public static string Default_Selection_Type {
            get {
                return ResourceManager.GetString("Default_Selection_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000.
        /// </summary>
        public static string Default_Simulations_Value {
            get {
                return ResourceManager.GetString("Default_Simulations_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll a six.
        /// </summary>
        public static string Dice_Condition_First {
            get {
                return ResourceManager.GetString("Dice_Condition_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation settings.
        /// </summary>
        public static string Header1_Settings_Calculation {
            get {
                return ResourceManager.GetString("Header1_Settings_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition settings.
        /// </summary>
        public static string Header2_Settings_Condition {
            get {
                return ResourceManager.GetString("Header2_Settings_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type settings.
        /// </summary>
        public static string Header2_Settings_Type {
            get {
                return ResourceManager.GetString("Header2_Settings_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Probability.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times..
        /// </summary>
        public static string String_Times {
            get {
                return ResourceManager.GetString("String_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal number of colors.
        /// </summary>
        public static string Text_Check_ColoredBalls_EqualNumberOfColors {
            get {
                return ResourceManager.GetString("Text_Check_ColoredBalls_EqualNumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select colors manually.
        /// </summary>
        public static string Text_Check_ColoredBalls_ManualColorSelection {
            get {
                return ResourceManager.GetString("Text_Check_ColoredBalls_ManualColorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color n: .
        /// </summary>
        public static string Text_ColoredBalls_ColorNumber {
            get {
                return ResourceManager.GetString("Text_ColoredBalls_ColorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors:.
        /// </summary>
        public static string Text_ColoredBalls_NumberOfColors {
            get {
                return ResourceManager.GetString("Text_ColoredBalls_NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition:.
        /// </summary>
        public static string Text_Condition {
            get {
                return ResourceManager.GetString("Text_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of taken balls:.
        /// </summary>
        public static string Text_Condition_ColoredBalls_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Text_Condition_ColoredBalls_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dice rolls:.
        /// </summary>
        public static string Text_Condition_Dice_NumberOfTakenItems {
            get {
                return ResourceManager.GetString("Text_Condition_Dice_NumberOfTakenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition was met.
        /// </summary>
        public static string Text_ConditionsMet {
            get {
                return ResourceManager.GetString("Text_ConditionsMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side number.
        /// </summary>
        public static string Text_Dice_Side {
            get {
                return ResourceManager.GetString("Text_Dice_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of balls:.
        /// </summary>
        public static string Text_Pool_Size_ColoredBalls {
            get {
                return ResourceManager.GetString("Text_Pool_Size_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sides:.
        /// </summary>
        public static string Text_Pool_Size_Dice {
            get {
                return ResourceManager.GetString("Text_Pool_Size_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of condition is.
        /// </summary>
        public static string Text_Probability {
            get {
                return ResourceManager.GetString("Text_Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Text_Selection_Type {
            get {
                return ResourceManager.GetString("Text_Selection_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of simulations:.
        /// </summary>
        public static string Text_Simulations {
            get {
                return ResourceManager.GetString("Text_Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation ran.
        /// </summary>
        public static string Text_SimulationsRun {
            get {
                return ResourceManager.GetString("Text_SimulationsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: Colored balls.
        /// </summary>
        public static string Type_ColoredBalls {
            get {
                return ResourceManager.GetString("Type_ColoredBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: Dice.
        /// </summary>
        public static string Type_Dice {
            get {
                return ResourceManager.GetString("Type_Dice", resourceCulture);
            }
        }
    }
}
