//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties.LocalizableResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColoredBallsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColoredBallsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.LocalizableResources.ColoredBallsResources", typeof(ColoredBallsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available colors.
        /// </summary>
        public static string ColorPicker_AvailableColorsHeader {
            get {
                return ResourceManager.GetString("ColorPicker_AvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No colors available.
        /// </summary>
        public static string ColorPicker_NoAvailableColorsHeader {
            get {
                return ResourceManager.GetString("ColorPicker_NoAvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color.
        /// </summary>
        public static string ComboBox_ColorSelection_Text {
            get {
                return ResourceManager.GetString("ComboBox_ColorSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string IntegerUpDown_ColorNumber_Text {
            get {
                return ResourceManager.GetString("IntegerUpDown_ColorNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string IntegerUpDown_NumberOfBalls_Text {
            get {
                return ResourceManager.GetString("IntegerUpDown_NumberOfBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string IntegerUpDown_NumberOfColors_Text {
            get {
                return ResourceManager.GetString("IntegerUpDown_NumberOfColors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string IntegerUpDown_NumberOfTakenBalls_Text {
            get {
                return ResourceManager.GetString("IntegerUpDown_NumberOfTakenBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color count:.
        /// </summary>
        public static string Label_ColorCount_Content {
            get {
                return ResourceManager.GetString("Label_ColorCount_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color:.
        /// </summary>
        public static string Label_ColorPicker_Content {
            get {
                return ResourceManager.GetString("Label_ColorPicker_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of balls:.
        /// </summary>
        public static string Label_NumberOfBalls_Content {
            get {
                return ResourceManager.GetString("Label_NumberOfBalls_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors:.
        /// </summary>
        public static string Label_NumberOfColors_Content {
            get {
                return ResourceManager.GetString("Label_NumberOfColors_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of taken balls:.
        /// </summary>
        public static string Label_NumberOfTakenBalls_Content {
            get {
                return ResourceManager.GetString("Label_NumberOfTakenBalls_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of these balls are.
        /// </summary>
        public static string String_BeforeColorNamePlural {
            get {
                return ResourceManager.GetString("String_BeforeColorNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of these balls is.
        /// </summary>
        public static string String_BeforeColorNameSingular {
            get {
                return ResourceManager.GetString("String_BeforeColorNameSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ball taken is.
        /// </summary>
        public static string String_CalculationAction {
            get {
                return ResourceManager.GetString("String_CalculationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balls,.
        /// </summary>
        public static string String_PoolItem {
            get {
                return ResourceManager.GetString("String_PoolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bag of colored balls, that can have from nine to a hundred balls..
        /// </summary>
        public static string String_TypeInfo {
            get {
                return ResourceManager.GetString("String_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: ColoredBalls.
        /// </summary>
        public static string String_TypeName {
            get {
                return ResourceManager.GetString("String_TypeName", resourceCulture);
            }
        }
    }
}
