//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties.LocalizableResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberStringsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberStringsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.LocalizableResources.NumberStringsResources" +
                            "", typeof(NumberStringsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighteen.
        /// </summary>
        internal static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the eighth.
        /// </summary>
        internal static string Eighth {
            get {
                return ResourceManager.GetString("Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty.
        /// </summary>
        internal static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty eight.
        /// </summary>
        internal static string Eighty_eight {
            get {
                return ResourceManager.GetString("Eighty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty five.
        /// </summary>
        internal static string Eighty_five {
            get {
                return ResourceManager.GetString("Eighty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty four.
        /// </summary>
        internal static string Eighty_four {
            get {
                return ResourceManager.GetString("Eighty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty nine.
        /// </summary>
        internal static string Eighty_nine {
            get {
                return ResourceManager.GetString("Eighty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty one.
        /// </summary>
        internal static string Eighty_one {
            get {
                return ResourceManager.GetString("Eighty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty seven.
        /// </summary>
        internal static string Eighty_seven {
            get {
                return ResourceManager.GetString("Eighty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty six.
        /// </summary>
        internal static string Eighty_six {
            get {
                return ResourceManager.GetString("Eighty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty three.
        /// </summary>
        internal static string Eighty_three {
            get {
                return ResourceManager.GetString("Eighty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty two.
        /// </summary>
        internal static string Eighty_two {
            get {
                return ResourceManager.GetString("Eighty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleven.
        /// </summary>
        internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteen.
        /// </summary>
        internal static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the fifth.
        /// </summary>
        internal static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty.
        /// </summary>
        internal static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty eight.
        /// </summary>
        internal static string Fifty_eight {
            get {
                return ResourceManager.GetString("Fifty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty five.
        /// </summary>
        internal static string Fifty_five {
            get {
                return ResourceManager.GetString("Fifty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty four.
        /// </summary>
        internal static string Fifty_four {
            get {
                return ResourceManager.GetString("Fifty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty nine.
        /// </summary>
        internal static string Fifty_nine {
            get {
                return ResourceManager.GetString("Fifty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty one.
        /// </summary>
        internal static string Fifty_one {
            get {
                return ResourceManager.GetString("Fifty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty seven.
        /// </summary>
        internal static string Fifty_seven {
            get {
                return ResourceManager.GetString("Fifty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty six.
        /// </summary>
        internal static string Fifty_six {
            get {
                return ResourceManager.GetString("Fifty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty three.
        /// </summary>
        internal static string Fifty_three {
            get {
                return ResourceManager.GetString("Fifty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty two.
        /// </summary>
        internal static string Fifty_two {
            get {
                return ResourceManager.GetString("Fifty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the first.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        internal static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the fourth.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty.
        /// </summary>
        internal static string Fourty {
            get {
                return ResourceManager.GetString("Fourty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty eight.
        /// </summary>
        internal static string Fourty_eight {
            get {
                return ResourceManager.GetString("Fourty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty five.
        /// </summary>
        internal static string Fourty_five {
            get {
                return ResourceManager.GetString("Fourty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty four.
        /// </summary>
        internal static string Fourty_four {
            get {
                return ResourceManager.GetString("Fourty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty nine.
        /// </summary>
        internal static string Fourty_nine {
            get {
                return ResourceManager.GetString("Fourty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty one.
        /// </summary>
        internal static string Fourty_one {
            get {
                return ResourceManager.GetString("Fourty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty seven.
        /// </summary>
        internal static string Fourty_seven {
            get {
                return ResourceManager.GetString("Fourty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty six.
        /// </summary>
        internal static string Fourty_six {
            get {
                return ResourceManager.GetString("Fourty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty three.
        /// </summary>
        internal static string Fourty_three {
            get {
                return ResourceManager.GetString("Fourty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty two.
        /// </summary>
        internal static string Fourty_two {
            get {
                return ResourceManager.GetString("Fourty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hundred.
        /// </summary>
        internal static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineteen.
        /// </summary>
        internal static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety.
        /// </summary>
        internal static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety eight.
        /// </summary>
        internal static string Ninety_eight {
            get {
                return ResourceManager.GetString("Ninety-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety five.
        /// </summary>
        internal static string Ninety_five {
            get {
                return ResourceManager.GetString("Ninety-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety four.
        /// </summary>
        internal static string Ninety_four {
            get {
                return ResourceManager.GetString("Ninety-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety nine.
        /// </summary>
        internal static string Ninety_nine {
            get {
                return ResourceManager.GetString("Ninety-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety one.
        /// </summary>
        internal static string Ninety_one {
            get {
                return ResourceManager.GetString("Ninety-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety seven.
        /// </summary>
        internal static string Ninety_seven {
            get {
                return ResourceManager.GetString("Ninety-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety six.
        /// </summary>
        internal static string Ninety_six {
            get {
                return ResourceManager.GetString("Ninety-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety three.
        /// </summary>
        internal static string Ninety_three {
            get {
                return ResourceManager.GetString("Ninety-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety two.
        /// </summary>
        internal static string Ninety_two {
            get {
                return ResourceManager.GetString("Ninety-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ninth.
        /// </summary>
        internal static string Ninth {
            get {
                return ResourceManager.GetString("Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventeen.
        /// </summary>
        internal static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the seventh.
        /// </summary>
        internal static string Seventh {
            get {
                return ResourceManager.GetString("Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy.
        /// </summary>
        internal static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy eight.
        /// </summary>
        internal static string Seventy_eight {
            get {
                return ResourceManager.GetString("Seventy-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy five.
        /// </summary>
        internal static string Seventy_five {
            get {
                return ResourceManager.GetString("Seventy-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy four.
        /// </summary>
        internal static string Seventy_four {
            get {
                return ResourceManager.GetString("Seventy-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy nine.
        /// </summary>
        internal static string Seventy_nine {
            get {
                return ResourceManager.GetString("Seventy-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy one.
        /// </summary>
        internal static string Seventy_one {
            get {
                return ResourceManager.GetString("Seventy-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy seven.
        /// </summary>
        internal static string Seventy_seven {
            get {
                return ResourceManager.GetString("Seventy-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy six.
        /// </summary>
        internal static string Seventy_six {
            get {
                return ResourceManager.GetString("Seventy-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy three.
        /// </summary>
        internal static string Seventy_three {
            get {
                return ResourceManager.GetString("Seventy-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy two.
        /// </summary>
        internal static string Seventy_two {
            get {
                return ResourceManager.GetString("Seventy-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteen.
        /// </summary>
        internal static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the sixth.
        /// </summary>
        internal static string Sixth {
            get {
                return ResourceManager.GetString("Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty.
        /// </summary>
        internal static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty eight.
        /// </summary>
        internal static string Sixty_eight {
            get {
                return ResourceManager.GetString("Sixty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty five.
        /// </summary>
        internal static string Sixty_five {
            get {
                return ResourceManager.GetString("Sixty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty four.
        /// </summary>
        internal static string Sixty_four {
            get {
                return ResourceManager.GetString("Sixty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty nine.
        /// </summary>
        internal static string Sixty_nine {
            get {
                return ResourceManager.GetString("Sixty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty one.
        /// </summary>
        internal static string Sixty_one {
            get {
                return ResourceManager.GetString("Sixty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty seven.
        /// </summary>
        internal static string Sixty_seven {
            get {
                return ResourceManager.GetString("Sixty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty six.
        /// </summary>
        internal static string Sixty_six {
            get {
                return ResourceManager.GetString("Sixty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty three.
        /// </summary>
        internal static string Sixty_three {
            get {
                return ResourceManager.GetString("Sixty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty two.
        /// </summary>
        internal static string Sixty_two {
            get {
                return ResourceManager.GetString("Sixty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenth.
        /// </summary>
        internal static string Tenth {
            get {
                return ResourceManager.GetString("Tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteen.
        /// </summary>
        internal static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty.
        /// </summary>
        internal static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty eight.
        /// </summary>
        internal static string Thirty_eight {
            get {
                return ResourceManager.GetString("Thirty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty five.
        /// </summary>
        internal static string Thirty_five {
            get {
                return ResourceManager.GetString("Thirty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty four.
        /// </summary>
        internal static string Thirty_four {
            get {
                return ResourceManager.GetString("Thirty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty nine.
        /// </summary>
        internal static string Thirty_nine {
            get {
                return ResourceManager.GetString("Thirty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty one.
        /// </summary>
        internal static string Thirty_one {
            get {
                return ResourceManager.GetString("Thirty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty seven.
        /// </summary>
        internal static string Thirty_seven {
            get {
                return ResourceManager.GetString("Thirty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty six.
        /// </summary>
        internal static string Thirty_six {
            get {
                return ResourceManager.GetString("Thirty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty three.
        /// </summary>
        internal static string Thirty_three {
            get {
                return ResourceManager.GetString("Thirty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty two.
        /// </summary>
        internal static string Thirty_two {
            get {
                return ResourceManager.GetString("Thirty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty.
        /// </summary>
        internal static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty eight.
        /// </summary>
        internal static string Twenty_eight {
            get {
                return ResourceManager.GetString("Twenty-eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty five.
        /// </summary>
        internal static string Twenty_five {
            get {
                return ResourceManager.GetString("Twenty-five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty four.
        /// </summary>
        internal static string Twenty_four {
            get {
                return ResourceManager.GetString("Twenty-four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty nine.
        /// </summary>
        internal static string Twenty_nine {
            get {
                return ResourceManager.GetString("Twenty-nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty one.
        /// </summary>
        internal static string Twenty_one {
            get {
                return ResourceManager.GetString("Twenty-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty seven.
        /// </summary>
        internal static string Twenty_seven {
            get {
                return ResourceManager.GetString("Twenty-seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty six.
        /// </summary>
        internal static string Twenty_six {
            get {
                return ResourceManager.GetString("Twenty-six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty three.
        /// </summary>
        internal static string Twenty_three {
            get {
                return ResourceManager.GetString("Twenty-three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty two.
        /// </summary>
        internal static string Twenty_two {
            get {
                return ResourceManager.GetString("Twenty-two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
