using System.Collections.Generic;
using System.Collections.ObjectModel;
using LocalResx = ExperimentalProbability.Contracts.Properties.NumberStringsResources;

namespace ExperimentalProbability.Contracts.Utilities
{
    public static class NumberTranslater
    {
        public static readonly ReadOnlyDictionary<int, string> NumberToWord = new ReadOnlyDictionary<int, string>(
            new Dictionary<int, string>()
            {
                { 0, LocalResx.Zero },
                { 1, LocalResx.One },
                { 2, LocalResx.Two },
                { 3, LocalResx.Three },
                { 4, LocalResx.Four },
                { 5, LocalResx.Five },
                { 6, LocalResx.Six },
                { 7, LocalResx.Seven },
                { 8, LocalResx.Eight },
                { 9, LocalResx.Nine },
                { 10, LocalResx.Ten },
                { 11, LocalResx.Eleven },
                { 12, LocalResx.Twelve },
                { 13, LocalResx.Thirteen },
                { 14, LocalResx.Fourteen },
                { 15, LocalResx.Fifteen },
                { 16, LocalResx.Sixteen },
                { 17, LocalResx.Seventeen },
                { 18, LocalResx.Eighteen },
                { 19, LocalResx.Nineteen },
                { 20, LocalResx.Twenty },
                { 21, LocalResx.Twenty_one },
                { 22, LocalResx.Twenty_two },
                { 23, LocalResx.Twenty_three },
                { 24, LocalResx.Twenty_four },
                { 25, LocalResx.Twenty_five },
                { 26, LocalResx.Twenty_six },
                { 27, LocalResx.Twenty_seven },
                { 28, LocalResx.Twenty_eight },
                { 29, LocalResx.Twenty_nine },
                { 30, LocalResx.Thirty },
                { 31, LocalResx.Thirty_one },
                { 32, LocalResx.Thirty_two },
                { 33, LocalResx.Thirty_three },
                { 34, LocalResx.Thirty_four },
                { 35, LocalResx.Thirty_five },
                { 36, LocalResx.Thirty_six },
                { 37, LocalResx.Thirty_seven },
                { 38, LocalResx.Thirty_eight },
                { 39, LocalResx.Thirty_nine },
                { 40, LocalResx.Fourty },
                { 41, LocalResx.Fourty_one },
                { 42, LocalResx.Fourty_two },
                { 43, LocalResx.Fourty_three },
                { 44, LocalResx.Fourty_four },
                { 45, LocalResx.Fourty_five },
                { 46, LocalResx.Fourty_six },
                { 47, LocalResx.Fourty_seven },
                { 48, LocalResx.Fourty_eight },
                { 49, LocalResx.Fourty_nine },
                { 50, LocalResx.Fifty },
                { 51, LocalResx.Fifty_one },
                { 52, LocalResx.Fifty_two },
                { 53, LocalResx.Fifty_three },
                { 54, LocalResx.Fifty_four },
                { 55, LocalResx.Fifty_five },
                { 56, LocalResx.Fifty_six },
                { 57, LocalResx.Fifty_seven },
                { 58, LocalResx.Fifty_eight },
                { 59, LocalResx.Fifty_nine },
                { 60, LocalResx.Sixty },
                { 61, LocalResx.Sixty_one },
                { 62, LocalResx.Sixty_two },
                { 63, LocalResx.Sixty_three },
                { 64, LocalResx.Sixty_four },
                { 65, LocalResx.Sixty_five },
                { 66, LocalResx.Sixty_six },
                { 67, LocalResx.Sixty_seven },
                { 68, LocalResx.Sixty_eight },
                { 69, LocalResx.Sixty_nine },
                { 70, LocalResx.Seventy },
                { 71, LocalResx.Seventy_one },
                { 72, LocalResx.Seventy_two },
                { 73, LocalResx.Seventy_three },
                { 74, LocalResx.Seventy_four },
                { 75, LocalResx.Seventy_five },
                { 76, LocalResx.Seventy_six },
                { 77, LocalResx.Seventy_seven },
                { 78, LocalResx.Seventy_eight },
                { 79, LocalResx.Seventy_nine },
                { 80, LocalResx.Eighty },
                { 81, LocalResx.Eighty_one },
                { 82, LocalResx.Eighty_two },
                { 83, LocalResx.Eighty_three },
                { 84, LocalResx.Eighty_four },
                { 85, LocalResx.Eighty_five },
                { 86, LocalResx.Eighty_six },
                { 87, LocalResx.Eighty_seven },
                { 88, LocalResx.Eighty_eight },
                { 89, LocalResx.Eighty_nine },
                { 90, LocalResx.Ninety },
                { 91, LocalResx.Ninety_one },
                { 92, LocalResx.Ninety_two },
                { 93, LocalResx.Ninety_three },
                { 94, LocalResx.Ninety_four },
                { 95, LocalResx.Ninety_five },
                { 96, LocalResx.Ninety_six },
                { 97, LocalResx.Ninety_seven },
                { 98, LocalResx.Ninety_eight },
                { 99, LocalResx.Ninety_nine },
                { 100, LocalResx.Hundred },
            });

        public static readonly ReadOnlyDictionary<int, string> NumberToPosition = new ReadOnlyDictionary<int, string>(
            new Dictionary<int, string>()
            {
                { 0, LocalResx.First },
                { 1, LocalResx.Second },
                { 2, LocalResx.Third },
                { 3, LocalResx.Fourth },
                { 4, LocalResx.Fifth },
                { 5, LocalResx.Sixth },
                { 6, LocalResx.Seventh },
                { 7, LocalResx.Eighth },
                { 8, LocalResx.Ninth },
                { 9, LocalResx.Tenth },
            });
    }
}
