//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.General." +
                            "Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide - Condition configuration.
        /// </summary>
        public static string Condition_Expander_Hide {
            get {
                return ResourceManager.GetString("Condition_Expander_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show - Condition configuration.
        /// </summary>
        public static string Condition_Expander_Show {
            get {
                return ResourceManager.GetString("Condition_Expander_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This calculation works with a pool, that consists of a.
        /// </summary>
        public static string Description_CalculationInfo {
            get {
                return ResourceManager.GetString("Description_CalculationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition you are looking for is that:.
        /// </summary>
        public static string Description_ConditionInfo {
            get {
                return ResourceManager.GetString("Description_ConditionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the pool is made out of:.
        /// </summary>
        public static string Description_PoolInfo {
            get {
                return ResourceManager.GetString("Description_PoolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool visualization.
        /// </summary>
        public static string Header_Visualization {
            get {
                return ResourceManager.GetString("Header_Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide - Pool configuration.
        /// </summary>
        public static string Pool_Expander_Hide {
            get {
                return ResourceManager.GetString("Pool_Expander_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show - Pool configuration.
        /// </summary>
        public static string Pool_Expander_Show {
            get {
                return ResourceManager.GetString("Pool_Expander_Show", resourceCulture);
            }
        }
    }
}
