//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.UI.Properties.Types.ColoredBalss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.UI.Properties.Types.ColoredBalss.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorBlack {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorBlue {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorBrown {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorGray {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorGreen {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorOrange {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorRed {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorViolet {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorWhite {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Item_ColorYellow {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Item_ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color.
        /// </summary>
        public static string Settings_ComboBox_ColorSelection_Text {
            get {
                return ResourceManager.GetString("Settings_ComboBox_ColorSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Settings_IntegerUpDown_ColorNumber_Text {
            get {
                return ResourceManager.GetString("Settings_IntegerUpDown_ColorNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Settings_IntegerUpDown_NumberOfBalls_Text {
            get {
                return ResourceManager.GetString("Settings_IntegerUpDown_NumberOfBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Settings_IntegerUpDown_NumberOfColors_Text {
            get {
                return ResourceManager.GetString("Settings_IntegerUpDown_NumberOfColors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Settings_IntegerUpDown_NumberOfTakenBalls_Text {
            get {
                return ResourceManager.GetString("Settings_IntegerUpDown_NumberOfTakenBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color n:.
        /// </summary>
        public static string Settings_TextBlock_ColorNumber_Text {
            get {
                return ResourceManager.GetString("Settings_TextBlock_ColorNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored balls settings.
        /// </summary>
        public static string Settings_TextBlock_Header2_Text {
            get {
                return ResourceManager.GetString("Settings_TextBlock_Header2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of balls:.
        /// </summary>
        public static string Settings_TextBlock_NumberOfBalls_Text {
            get {
                return ResourceManager.GetString("Settings_TextBlock_NumberOfBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors:.
        /// </summary>
        public static string Settings_TextBlock_NumberOfColors_Text {
            get {
                return ResourceManager.GetString("Settings_TextBlock_NumberOfColors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of taken balls:.
        /// </summary>
        public static string Settings_TextBlock_NumberOfTakenBalls_Text {
            get {
                return ResourceManager.GetString("Settings_TextBlock_NumberOfTakenBalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool: ColoredBalls.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
    }
}
