//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.Dice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.Dice.Res" +
                            "ources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to side rolled is.
        /// </summary>
        public static string CalcAction {
            get {
                return ResourceManager.GetString("CalcAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die, that can have four, six, eight, ten, twelve or twenty sides..
        /// </summary>
        public static string CalculationInfo {
            get {
                return ResourceManager.GetString("CalculationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six-sided Die.
        /// </summary>
        public static string Dice_Cube {
            get {
                return ResourceManager.GetString("Dice_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve-sided Die.
        /// </summary>
        public static string Dice_Dodecahedron {
            get {
                return ResourceManager.GetString("Dice_Dodecahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-sided Die.
        /// </summary>
        public static string Dice_Icosahedron {
            get {
                return ResourceManager.GetString("Dice_Icosahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight-sided Die.
        /// </summary>
        public static string Dice_Octahedron {
            get {
                return ResourceManager.GetString("Dice_Octahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten-sided Die.
        /// </summary>
        public static string Dice_PentagonalTrapezohedron {
            get {
                return ResourceManager.GetString("Dice_PentagonalTrapezohedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four-sided Die.
        /// </summary>
        public static string Dice_Tetrahedron {
            get {
                return ResourceManager.GetString("Dice_Tetrahedron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a dice:.
        /// </summary>
        public static string DiceSelector {
            get {
                return ResourceManager.GetString("DiceSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Calculation: Dice.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Dice.
        /// </summary>
        public static string ElementName_Dice {
            get {
                return ResourceManager.GetString("ElementName_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rolls.
        /// </summary>
        public static string ElementName_NumberOfRolls {
            get {
                return ResourceManager.GetString("ElementName_NumberOfRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string ElementName_Roll {
            get {
                return ResourceManager.GetString("ElementName_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rolls:.
        /// </summary>
        public static string NumberOfRolls {
            get {
                return ResourceManager.GetString("NumberOfRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a side:.
        /// </summary>
        public static string SidePicker {
            get {
                return ResourceManager.GetString("SidePicker", resourceCulture);
            }
        }
    }
}
