//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Shell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Shell.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y = (x^2 - 4) * sin(x).
        /// </summary>
        public static string AreaCalc {
            get {
                return ResourceManager.GetString("AreaCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag with colored balls.
        /// </summary>
        public static string ColoredBallsCalc {
            get {
                return ResourceManager.GetString("ColoredBallsCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dice.
        /// </summary>
        public static string DiceCalc {
            get {
                return ResourceManager.GetString("DiceCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Probability.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x^2 + y^2 = 1.
        /// </summary>
        public static string PiCalc {
            get {
                return ResourceManager.GetString("PiCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Calculations:.
        /// </summary>
        public static string PoolCalcs {
            get {
                return ResourceManager.GetString("PoolCalcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-D Plane Calculations:.
        /// </summary>
        public static string TwoDPlaneCalcs {
            get {
                return ResourceManager.GetString("TwoDPlaneCalcs", resourceCulture);
            }
        }
    }
}
