//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.ColoredBalls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Calculations.Pool.ColoredB" +
                            "alls.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Colors.
        /// </summary>
        public static string AvailableColorsHeader {
            get {
                return ResourceManager.GetString("AvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balls are.
        /// </summary>
        public static string BeforeColorPlural {
            get {
                return ResourceManager.GetString("BeforeColorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ball is.
        /// </summary>
        public static string BeforeColorSingular {
            get {
                return ResourceManager.GetString("BeforeColorSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taken ball is.
        /// </summary>
        public static string CalcAction {
            get {
                return ResourceManager.GetString("CalcAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bag of colored balls, that can have from two to hundred balls..
        /// </summary>
        public static string CalculationInfo {
            get {
                return ResourceManager.GetString("CalculationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color:.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color count:.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Calculation: Bag of Colored Balls.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Color.
        /// </summary>
        public static string ElementName_ConditionColor {
            get {
                return ResourceManager.GetString("ElementName_ConditionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Count.
        /// </summary>
        public static string ElementName_Counter {
            get {
                return ResourceManager.GetString("ElementName_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the sum of all Color Counts.
        /// </summary>
        public static string ElementName_CounterSum {
            get {
                return ResourceManager.GetString("ElementName_CounterSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Balls.
        /// </summary>
        public static string ElementName_NumberOfBalls {
            get {
                return ResourceManager.GetString("ElementName_NumberOfBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Colors.
        /// </summary>
        public static string ElementName_NumberOfColors {
            get {
                return ResourceManager.GetString("ElementName_NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Taken Balls.
        /// </summary>
        public static string ElementName_NumberOfTakenBalls {
            get {
                return ResourceManager.GetString("ElementName_NumberOfTakenBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Color.
        /// </summary>
        public static string ElementName_PoolColor {
            get {
                return ResourceManager.GetString("ElementName_PoolColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of balls:.
        /// </summary>
        public static string NumberOfBalls {
            get {
                return ResourceManager.GetString("NumberOfBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors:.
        /// </summary>
        public static string NumberOfColors {
            get {
                return ResourceManager.GetString("NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of taken balls:.
        /// </summary>
        public static string NumberOfTakenBalls {
            get {
                return ResourceManager.GetString("NumberOfTakenBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colored balls..
        /// </summary>
        public static string PoolItem {
            get {
                return ResourceManager.GetString("PoolItem", resourceCulture);
            }
        }
    }
}
