//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalProbability.Contracts.Properties.Resources.Tutorial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalProbability.Contracts.Properties.Resources.Tutorial.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If in doubt this tab can be opened again from the menu.
        /// </summary>
        public static string FifthFirstStep {
            get {
                return ResourceManager.GetString("FifthFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All calculations configuration is only lost after the application is closed.
        /// </summary>
        public static string FifthSecondStep {
            get {
                return ResourceManager.GetString("FifthSecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat these steps indefinitely.
        /// </summary>
        public static string FifthStep {
            get {
                return ResourceManager.GetString("FifthStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all you need to choose a calculation in the menu.
        /// </summary>
        public static string FirstStep {
            get {
                return ResourceManager.GetString("FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If any errors pop up follow the given instructions..
        /// </summary>
        public static string FourthFirstStep {
            get {
                return ResourceManager.GetString("FourthFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no errors pop up wait for all results..
        /// </summary>
        public static string FourthSecondStep {
            get {
                return ResourceManager.GetString("FourthSecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the current calculation.
        /// </summary>
        public static string FourthStep {
            get {
                return ResourceManager.GetString("FourthStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the pool that will be used to your liking.
        /// </summary>
        public static string PoolFirstStep {
            get {
                return ResourceManager.GetString("PoolFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the condition you are looking for.
        /// </summary>
        public static string PoolSecondStep {
            get {
                return ResourceManager.GetString("PoolSecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up how many simulations of chosen calculation you want to run.
        /// </summary>
        public static string SecondStep {
            get {
                return ResourceManager.GetString("SecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps for pool calculations.
        /// </summary>
        public static string ThirdFirstStep {
            get {
                return ResourceManager.GetString("ThirdFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps for 2-D plane calculations.
        /// </summary>
        public static string ThirdSecondStep {
            get {
                return ResourceManager.GetString("ThirdSecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow next steps based on chosen calculation.
        /// </summary>
        public static string ThirdStep {
            get {
                return ResourceManager.GetString("ThirdStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to set up, you can skip to the fourth step.
        /// </summary>
        public static string TwoDPlaneFirstStep {
            get {
                return ResourceManager.GetString("TwoDPlaneFirstStep", resourceCulture);
            }
        }
    }
}
